/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as PasseiosRouteImport } from './routes/passeios'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PagamentoSucessoRouteImport } from './routes/pagamento.sucesso'
import { Route as PagamentoCanceladoRouteImport } from './routes/pagamento.cancelado'
import { Route as ExperienciasSlugRouteImport } from './routes/experiencias.$slug'
import { Route as AdminVeiculosRouteImport } from './routes/admin.veiculos'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminPasseiosRouteImport } from './routes/admin.passeios'
import { Route as AdminGaleriaRouteImport } from './routes/admin.galeria'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as ApiInfinitepayWebhookRouteImport } from './routes/api/infinitepay.webhook'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const PasseiosRoute = PasseiosRouteImport.update({
  id: '/passeios',
  path: '/passeios',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PagamentoSucessoRoute = PagamentoSucessoRouteImport.update({
  id: '/pagamento/sucesso',
  path: '/pagamento/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoCanceladoRoute = PagamentoCanceladoRouteImport.update({
  id: '/pagamento/cancelado',
  path: '/pagamento/cancelado',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasSlugRoute = ExperienciasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExperienciasRoute,
} as any)
const AdminVeiculosRoute = AdminVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPasseiosRoute = AdminPasseiosRouteImport.update({
  id: '/passeios',
  path: '/passeios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGaleriaRoute = AdminGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const ApiInfinitepayWebhookRoute = ApiInfinitepayWebhookRouteImport.update({
  id: '/api/infinitepay/webhook',
  path: '/api/infinitepay/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/experiencias': typeof ExperienciasRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/passeios': typeof PasseiosRoute
  '/reservar': typeof ReservarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/galeria': typeof AdminGaleriaRoute
  '/admin/passeios': typeof AdminPasseiosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/experiencias/$slug': typeof ExperienciasSlugRoute
  '/pagamento/cancelado': typeof PagamentoCanceladoRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/admin/': typeof AdminIndexRoute
  '/api/infinitepay/webhook': typeof ApiInfinitepayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/experiencias': typeof ExperienciasRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/passeios': typeof PasseiosRoute
  '/reservar': typeof ReservarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/galeria': typeof AdminGaleriaRoute
  '/admin/passeios': typeof AdminPasseiosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/experiencias/$slug': typeof ExperienciasSlugRoute
  '/pagamento/cancelado': typeof PagamentoCanceladoRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/admin': typeof AdminIndexRoute
  '/api/infinitepay/webhook': typeof ApiInfinitepayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/experiencias': typeof ExperienciasRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/passeios': typeof PasseiosRoute
  '/reservar': typeof ReservarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/galeria': typeof AdminGaleriaRoute
  '/admin/passeios': typeof AdminPasseiosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/experiencias/$slug': typeof ExperienciasSlugRoute
  '/pagamento/cancelado': typeof PagamentoCanceladoRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/admin/': typeof AdminIndexRoute
  '/api/infinitepay/webhook': typeof ApiInfinitepayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contato'
    | '/experiencias'
    | '/galeria'
    | '/passeios'
    | '/reservar'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/galeria'
    | '/admin/passeios'
    | '/admin/reservas'
    | '/admin/veiculos'
    | '/experiencias/$slug'
    | '/pagamento/cancelado'
    | '/pagamento/sucesso'
    | '/admin/'
    | '/api/infinitepay/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/experiencias'
    | '/galeria'
    | '/passeios'
    | '/reservar'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/galeria'
    | '/admin/passeios'
    | '/admin/reservas'
    | '/admin/veiculos'
    | '/experiencias/$slug'
    | '/pagamento/cancelado'
    | '/pagamento/sucesso'
    | '/admin'
    | '/api/infinitepay/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contato'
    | '/experiencias'
    | '/galeria'
    | '/passeios'
    | '/reservar'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/galeria'
    | '/admin/passeios'
    | '/admin/reservas'
    | '/admin/veiculos'
    | '/experiencias/$slug'
    | '/pagamento/cancelado'
    | '/pagamento/sucesso'
    | '/admin/'
    | '/api/infinitepay/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  ExperienciasRoute: typeof ExperienciasRouteWithChildren
  GaleriaRoute: typeof GaleriaRoute
  PasseiosRoute: typeof PasseiosRoute
  ReservarRoute: typeof ReservarRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  PagamentoCanceladoRoute: typeof PagamentoCanceladoRoute
  PagamentoSucessoRoute: typeof PagamentoSucessoRoute
  ApiInfinitepayWebhookRoute: typeof ApiInfinitepayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passeios': {
      id: '/passeios'
      path: '/passeios'
      fullPath: '/passeios'
      preLoaderRoute: typeof PasseiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias': {
      id: '/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof ExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pagamento/sucesso': {
      id: '/pagamento/sucesso'
      path: '/pagamento/sucesso'
      fullPath: '/pagamento/sucesso'
      preLoaderRoute: typeof PagamentoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/cancelado': {
      id: '/pagamento/cancelado'
      path: '/pagamento/cancelado'
      fullPath: '/pagamento/cancelado'
      preLoaderRoute: typeof PagamentoCanceladoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias/$slug': {
      id: '/experiencias/$slug'
      path: '/$slug'
      fullPath: '/experiencias/$slug'
      preLoaderRoute: typeof ExperienciasSlugRouteImport
      parentRoute: typeof ExperienciasRoute
    }
    '/admin/veiculos': {
      id: '/admin/veiculos'
      path: '/veiculos'
      fullPath: '/admin/veiculos'
      preLoaderRoute: typeof AdminVeiculosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/passeios': {
      id: '/admin/passeios'
      path: '/passeios'
      fullPath: '/admin/passeios'
      preLoaderRoute: typeof AdminPasseiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/galeria': {
      id: '/admin/galeria'
      path: '/galeria'
      fullPath: '/admin/galeria'
      preLoaderRoute: typeof AdminGaleriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/infinitepay/webhook': {
      id: '/api/infinitepay/webhook'
      path: '/api/infinitepay/webhook'
      fullPath: '/api/infinitepay/webhook'
      preLoaderRoute: typeof ApiInfinitepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminGaleriaRoute: typeof AdminGaleriaRoute
  AdminPasseiosRoute: typeof AdminPasseiosRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminVeiculosRoute: typeof AdminVeiculosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminGaleriaRoute: AdminGaleriaRoute,
  AdminPasseiosRoute: AdminPasseiosRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminVeiculosRoute: AdminVeiculosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ExperienciasRouteChildren {
  ExperienciasSlugRoute: typeof ExperienciasSlugRoute
}

const ExperienciasRouteChildren: ExperienciasRouteChildren = {
  ExperienciasSlugRoute: ExperienciasSlugRoute,
}

const ExperienciasRouteWithChildren = ExperienciasRoute._addFileChildren(
  ExperienciasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  ExperienciasRoute: ExperienciasRouteWithChildren,
  GaleriaRoute: GaleriaRoute,
  PasseiosRoute: PasseiosRoute,
  ReservarRoute: ReservarRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  PagamentoCanceladoRoute: PagamentoCanceladoRoute,
  PagamentoSucessoRoute: PagamentoSucessoRoute,
  ApiInfinitepayWebhookRoute: ApiInfinitepayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
