/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as PasseiosRouteImport } from './routes/passeios'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagamentoSucessoRouteImport } from './routes/pagamento.sucesso'
import { Route as PagamentoCanceladoRouteImport } from './routes/pagamento.cancelado'
import { Route as ApiInfinitepayWebhookRouteImport } from './routes/api/infinitepay.webhook'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const PasseiosRoute = PasseiosRouteImport.update({
  id: '/passeios',
  path: '/passeios',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoSucessoRoute = PagamentoSucessoRouteImport.update({
  id: '/pagamento/sucesso',
  path: '/pagamento/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoCanceladoRoute = PagamentoCanceladoRouteImport.update({
  id: '/pagamento/cancelado',
  path: '/pagamento/cancelado',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInfinitepayWebhookRoute = ApiInfinitepayWebhookRouteImport.update({
  id: '/api/infinitepay/webhook',
  path: '/api/infinitepay/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/passeios': typeof PasseiosRoute
  '/reservar': typeof ReservarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/pagamento/cancelado': typeof PagamentoCanceladoRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/api/infinitepay/webhook': typeof ApiInfinitepayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/passeios': typeof PasseiosRoute
  '/reservar': typeof ReservarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/pagamento/cancelado': typeof PagamentoCanceladoRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/api/infinitepay/webhook': typeof ApiInfinitepayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/passeios': typeof PasseiosRoute
  '/reservar': typeof ReservarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/pagamento/cancelado': typeof PagamentoCanceladoRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/api/infinitepay/webhook': typeof ApiInfinitepayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/galeria'
    | '/passeios'
    | '/reservar'
    | '/sitemap.xml'
    | '/sobre'
    | '/pagamento/cancelado'
    | '/pagamento/sucesso'
    | '/api/infinitepay/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/galeria'
    | '/passeios'
    | '/reservar'
    | '/sitemap.xml'
    | '/sobre'
    | '/pagamento/cancelado'
    | '/pagamento/sucesso'
    | '/api/infinitepay/webhook'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/galeria'
    | '/passeios'
    | '/reservar'
    | '/sitemap.xml'
    | '/sobre'
    | '/pagamento/cancelado'
    | '/pagamento/sucesso'
    | '/api/infinitepay/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  GaleriaRoute: typeof GaleriaRoute
  PasseiosRoute: typeof PasseiosRoute
  ReservarRoute: typeof ReservarRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  PagamentoCanceladoRoute: typeof PagamentoCanceladoRoute
  PagamentoSucessoRoute: typeof PagamentoSucessoRoute
  ApiInfinitepayWebhookRoute: typeof ApiInfinitepayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passeios': {
      id: '/passeios'
      path: '/passeios'
      fullPath: '/passeios'
      preLoaderRoute: typeof PasseiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/sucesso': {
      id: '/pagamento/sucesso'
      path: '/pagamento/sucesso'
      fullPath: '/pagamento/sucesso'
      preLoaderRoute: typeof PagamentoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/cancelado': {
      id: '/pagamento/cancelado'
      path: '/pagamento/cancelado'
      fullPath: '/pagamento/cancelado'
      preLoaderRoute: typeof PagamentoCanceladoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/infinitepay/webhook': {
      id: '/api/infinitepay/webhook'
      path: '/api/infinitepay/webhook'
      fullPath: '/api/infinitepay/webhook'
      preLoaderRoute: typeof ApiInfinitepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  GaleriaRoute: GaleriaRoute,
  PasseiosRoute: PasseiosRoute,
  ReservarRoute: ReservarRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  PagamentoCanceladoRoute: PagamentoCanceladoRoute,
  PagamentoSucessoRoute: PagamentoSucessoRoute,
  ApiInfinitepayWebhookRoute: ApiInfinitepayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
